export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DATA_DIR='data/hotpotqa_2wiki_searchr1'

export WANDB_MODE=offline
WAND_PROJECT='RAGRL'

export BASE_MODEL='/apdcephfs/share_303945704/hunyuan/plusonewu/Qwen2.5-7B'
export EXPERIMENT_NAME='LessNegative_AdjustPositive_TurnLevel_Ingroup_ratio0.5'
# export EVAL_MODEL_ROOT_PATH='/apdcephfs/share_303945704/hunyuan/plusonewu/searchr1_data/verl_checkpoints'
# export EXPERIMENT_NAME='3B-Prepend_think_token-goodquery_softpenalty-LessNegative_AdjustPositive_OnlyAnswer_Ingroup_ratio1.0-constant'
# export STEP=206
# export BASE_MODEL=$EVAL_MODEL_ROOT_PATH/$EXPERIMENT_NAME/actor/global_step_$STEP
# # export EXPERIMENT_NAME='baseline-NoWarmUp-prepend_think_token-LessNegative_TurnLevel_ratio0.95-step205ckpt-LLD'
# # export EXPERIMENT_NAME=$EXPERIMENT_NAME-step$STEP-easy_fast_test
# export EXPERIMENT_NAME=test

# set -x
export VLLM_ATTENTION_BACKEND=XFORMERS # vllm + qwen2-7b with flash_attn has some issues

# max_prompt_length = (config['training']['max_start_length'] + config['training']['max_response_length'] * (config['training']['max_turns'] - 1) + config['training']['max_obs_length'] * config['training']['max_turns'])
PYTHONUNBUFFERED=1 python -m verl.trainer.main_ppo_format \
    fast_test=false \
    start_global_step=0 \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_data_num=null \
    data.val_data_num=null \
    data.train_batch_size=512 \
    data.val_batch_size=256 \
    data.max_prompt_length=16384 \
    data.max_response_length=1024 \
    data.max_start_length=2048 \
    data.max_obs_length=2048 \
    data.shuffle_train_dataloader=True \
    algorithm.adv_estimator=grpo \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0 \
    actor_rollout_ref.actor.optim.warmup_style=cosine \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size=64 \
    actor_rollout_ref.actor.fsdp_config.param_offload=true \
    actor_rollout_ref.actor.fsdp_config.grad_offload=true \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.actor.loss_mode=vanilla \
    actor_rollout_ref.actor.gating=false \
    actor_rollout_ref.actor.pg_loss_ratio=1.75 \
    actor_rollout_ref.actor.pos_neg_both=false \
    actor_rollout_ref.actor.save_index.enable=false \
    actor_rollout_ref.actor.save_index.save_path=/apdcephfs/share_303945704/hunyuan/plusonewu/searchr1_data/entropy/$EXPERIMENT_NAME \
    actor_rollout_ref.actor.save_rollout.enable=true \
    actor_rollout_ref.actor.save_rollout.save_path=./rollout/$EXPERIMENT_NAME \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=128 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=128 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.clip_ratio=0.2 \
    algorithm.no_think_rl=false \
    actor_rollout_ref.rollout.n_agent=5 \
    actor_rollout_ref.rollout.temperature=1 \
    actor_rollout_ref.actor.state_masking=true \
    trainer.logger=['console','wandb'] \
    +trainer.val_only=false \
    +trainer.val_before_train=false \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=-1 \
    trainer.save_each_epoch=true \
    trainer.test_freq=500 \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=1 \
    trainer.total_training_steps=410 \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir=/apdcephfs/share_303945704/hunyuan/plusonewu/searchr1_data/verl_checkpoints/$EXPERIMENT_NAME \
    max_turns=4 \
    trainer.reward_function=f1 \
    retriever.url="http://127.0.0.1:8000/retrieve" \
    retriever.topk=20 \
    reranker.enable=true \
    reranker.select_num=3 \
    do_search=true \
    reward_model.valid_action_reward=false \
    reward_model.overlong_buffer_cfg.enable=false \
    reward_model.overlong_buffer_cfg.len=768 \
    reward_model.overlong_buffer_cfg.penalty_factor=1.0 \
    reward_model.enable_length_score=false \
    reward_model.more_turn=false \
    reward_model.format_reward=true \
    reward_model.query_reward=false \
    reward_model.query_score_calculator="old" \
    reward_model.query_doc_relevance.enable=false \
    reward_model.query_doc_relevance.desc="max" \
    reward_model.query_doc_relevance.segment_reward=false \
    reward_model.query_doc_relevance.split_mode="max" \
    reward_model.garbled_penalty.enable=false \
    reward_model.garbled_penalty.ppl_threshold=50 \
    reward_model.garbled_penalty.start_step=30 \
    reward_model.garbled_penalty.penalty_factor=0.1 \
    actor_rollout_ref.actor.remove_garbled=false \
    actor_rollout_ref.actor.garbled_regenerate.enable=false \
    actor_rollout_ref.actor.garbled_regenerate.start_step=30 \
    actor_rollout_ref.actor.garbled_regenerate.max_generate_turns=5 \
    actor_rollout_ref.actor.mask_void_turns.enable=false \
    actor_rollout_ref.actor.mask_void_turns.start_step=50 \
    actor_rollout_ref.actor.remove_all_same.enable=false \
    actor_rollout_ref.actor.remove_all_same.start_step=30 \
    actor_rollout_ref.actor.remove_all_same.threshold=0.2 \
    trainer.remove_format_reward.enable=false \
    trainer.remove_format_reward.start_step=50 \
    algorithm.neutral.enable=false \
    algorithm.neutral.threshold=0.6 \
    algorithm.use_global_std=false \
    algorithm.less_negative.enable=true \
    algorithm.less_negative.adjust_positive=true \
    algorithm.less_negative.clip=false \
    algorithm.less_negative.only_answer=false \
    algorithm.less_negative.in_group=true \
    algorithm.less_negative.turn_level=true \
    algorithm.less_negative.use_numel_ratio=false \
    algorithm.less_negative.target_ratio=0.5 \
    algorithm.less_negative.softpenalty_first=false \
    algorithm.less_negative.only_apply_risky=false \
    algorithm.less_negative.reset2zero=false \
    algorithm.segment_adv_type="softpenalty" \
    use_prelabed_rollout=false \
    difficulty_filter.enable=false \
    difficulty_filter.threshold=0.2 \
    difficulty_filter.start_step=0 \
    hard_replay.enable=false \
    hard_replay.hard_percentage=1.0 \
    hard_replay.use_older=false \
    mask_template_token.enable=false \
    mask_template_token.start_step=10 \
    prepend_think_token=false \
    2>&1 | tee log/$EXPERIMENT_NAME.log

python3 protect.py --g0 --g1 --g2 --g3 --g4 --g5 --g6 --g7 --num 3 --sleep 0 --burn
